apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: nav-report-uri
  namespace: default
  labels:
    team: aura
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /nav-report-uri/health
    initialDelay: 1
    timeout: 1
    periodSeconds: 3
    failureThreshold: 10
  readiness:
    path: /nav-report-uri/health
    initialDelay: 1
    timeout: 1
    periodSeconds: 3
    failureThreshold: 10
  replicas:
    min: 1
    max: 4
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - "https://nav-report-uri.prod-sbs.nais.io"
  resources:
    limits:
      cpu: 800m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 256Mi
